# Generated by Django 3.2.19 on 2023-06-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noticia',
            fields=[
                ('idnoticia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(blank=True, default='', max_length=200)),
                ('contenido', models.TextField(blank=True, default='', max_length=500)),
                ('categoria', models.IntegerField(blank=True, choices=[(1, 'Economía'), (2, 'Cambio climático')])),
            ],
        ),
    ]
