# Generated by Django 3.2.19 on 2023-06-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efectoEconomia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
